/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_negasoft_ByteProcess */

#ifndef _Included_org_negasoft_ByteProcess
#define _Included_org_negasoft_ByteProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_negasoft_ByteProcess
 * Method:    process
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_negasoft_ByteProcess_process
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
